// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NutriIndex.Products.Data;

#nullable disable

namespace NutriIndex.Products.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260718090020_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NutriIndex.Products.Models.Product", b =>
                {
                    b.Property<string>("Barcode")
                        .HasColumnType("text");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("CostPer100Kcal")
                        .HasPrecision(18, 1)
                        .HasColumnType("numeric(18,1)");

                    b.Property<decimal>("CostPer10gProtein")
                        .HasPrecision(18, 1)
                        .HasColumnType("numeric(18,1)");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Barcode");

                    b.ToTable("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
